drm/mediatek: mi_disp: Guard Logging Functions to avoid conflict after log disabled
../drivers/gpu/drm/mediatek/mi_disp/mi_disp_log.h:41:20: note: previous definition is here
static inline void disp_log_printk_utc(const char *fmt, ...) {}
                   ^
    ^
                  ^
../drivers/gpu/drm/mediatek/mi_disp/mi_disp_log.c:629:6: error: redefinition of 'mi_disp_log_exit'
void mi_disp_log_exit(void)
     ^
../drivers/gpu/drm/mediatek/mi_disp/mi_disp_log.h:39:20: note: previous definition is here
static inline void mi_disp_log_exit(void) {}
                   ^
4 errors generated.
make[5]: *** [../scripts/Makefile.build:359: drivers/gpu/drm/mediatek/mi_disp/mi_disp_log.o] Error 1
make[5]: *** Waiting for unfinished jobs....
make[4]: *** [../scripts/Makefile.build:674: drivers/gpu/drm/mediatek] Error 2
make[3]: *** [../scripts/Makefile.build:674: drivers/gpu/drm] Error 2
make[2]: *** [../scripts/Makefile.build:674: drivers/gpu] Error 2
make[1]: *** [/home/amardev/ares/kernel/Makefile:1262: drivers] Error 2
make[1]: Leaving directory '/home/amardev/ares/kernel/out'
make: *** [Makefile:153: sub-make] Error 2