drivers/usb: fix missing #endif
../drivers/usb/gadget/usbstring.c:65:2: error: unterminated conditional directive
 ^
../drivers/usb/gadget/usbstring.c:87:42: error: expected '}'
EXPORT_SYMBOL_GPL(usb_gadget_get_string);
                                         ^
../drivers/usb/gadget/usbstring.c:45:1: note: to match this '{'
{